name: solutions

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  days:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        day: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
        part: [1, 2]
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install Just
        uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: day ${{ matrix.day }} part ${{ matrix.part }}
        run: just run ${{ matrix.day }} ${{ matrix.part }}